### PR TITLE
Reorganize code in chirho.explainable

### PR DESCRIPTION
**Pull request by eb8680**

### CODE REVIEW

**Comment by eb8680** [comment]
That's unrelated to changes in this PR - see discussion in #305

**Comment by rfl-urbaniak** [comment]
The new structure is:

ops
	preempt

internals
	uniform_proposal
	soft_eq
	soft_neq

handlers
	components
		random_intervention
		undo_split
		consequent_differs

	preemptions
		Preemptions

	explanation
		SplitSubsets
		SearchForExplanation

**Review by rfl-urbaniak — CHANGES_REQUESTED** [review]
Possible suggestion, otherwise I'm fine with the shifts.
`test_uniform_proposal` still lives in `tests/explainable/defauts/test_defaults`, while `uniform_proposal` has been moved to `internals`. Double check if this is intended (or move to test_internals o/w).

**Comment by eb8680** [comment]
Good catch, I removed `test_defaults.py` and moved `test_uniform_proposal` to `test_internals.py`.

**Review by rfl-urbaniak — APPROVED** [review]

**Pull request merged**
