### PR TITLE
Fix inference in backdoor adjustment example

### LINKED ISSUE #257: Issue w/ Backdoor Adjustment Notebook
In the backdoor adjustment notebook, 

```
class BayesianBackdoorSATE(pyro.nn.PyroModule):

    def __init__(self, causal_model: BayesianBackdoor):
        super().__init__()
        self.conditioned_model = ConditionedBayesianBackdoor(causal_model)

    def forward(self, covariates_obs, training_obs, earnings_obs):

        # Sample jointly from observational and counterfactual distributions
        with MultiWorldCounterfactual(), do(actions={"training": 1. - training_obs}):
            _, _, earnings = self.conditioned_model(covariates_obs, training_obs, earnings_obs)

            # Evaluate the sample average treatment effect
            earnings_cf = gather(earnings, IndexSet(training={1}))
            earnings_f = gather(earnings, IndexSet(training={0}))
            ites = torch.where(training_obs == 1, earnings_cf - earnings_f, earnings_f - earnings_cf)
            return pyro.deterministic("SATE", torch.mean(ites, dim=-1, keepdim=True), event_dim=0)
```

Here ites should be replaced to `ites = torch.where(training_obs == 0, earnings_cf - earnings_f, earnings_f - earnings_cf)`. But in that case the estimated effect is negative. We should look through the model & data code to see what's going on, and make modifications to the model if needed.

### PR DESCRIPTION
**Pull request by eb8680**
Resolves #257

### CODE REVIEW

**Comment by eb8680** [comment]
The first commit fixes #257, I just need to update the text and add numbers from the original blog post before it can be merged.

**Comment by eb8680** [comment]
Updated, this is ready for review.

**Comment by agrawalraj** [comment]
Great taking a look now!

**Comment by agrawalraj** [comment]
Looks great, thanks!

**Review by agrawalraj — APPROVED** [review]

**Pull request merged**
