### PR TITLE
Add cut and examples to Sphinx docs

### PR DESCRIPTION
**Pull request by eb8680**
This PR makes the examples and library code from #229 show up in the ChiRho documentation

### CODE REVIEW

**Comment by SamWitty** [comment]
@eb8680, my understanding is that reviewing this PR involves only reviewing whether the docs/examples were added to build correctly and **not** the content and quality of the docs/examples themselves. My assumption is that the content itself has been previously reviewed.

**Comment by eb8680** [comment]
@SamWitty yes, that's right

**Comment by SamWitty** [comment]
I will review. I know @agrawalraj is busy prepping for his presentation tomorrow.

**Review by SamWitty — CHANGES_REQUESTED** [review]
The docs are being built correctly, so based on the discussion with @eb8680 this tightly scoped PR should be approved. That being said, I would highly recommend editing the original notebooks before merging.

Two issues that I see.

1. The sidebar for these notebooks is inconsistent because the main header in the notebook (marked using a single #) does not include "Example: ..." and the References are marked using a single # leading to them being a top-level item. See the screenshot below.


Screenshot 2023-08-07 at 9 55 35 AM

2. The example table of contents in the sidebar is somewhat unreadable because it includes full sentences, where previous examples include just a small phrase.

Screenshot 2023-08-07 at 10 00 23 AM

In addition, the notebooks do not include table of contents, and the formatting the references is incomplete in the SDID notebook.

**Comment by SamWitty** [comment]
I'll go ahead and make my requested changes in a separate PR, and then come back and merge this once that's merged.

**Review by SamWitty — APPROVED** [review]
Looks good. Confirmed with a fresh build that the docs and github landing page render correctly.

**Pull request merged**
